# Generated by Django 4.1.7 on 2023-08-05 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitado',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='invitado',
            name='nombre',
        ),
        migrations.AddField(
            model_name='invitado',
            name='acompanantes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invitado',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='invitado',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='invitado',
            name='tipo_comida',
            field=models.CharField(blank=True, choices=[('vegano', 'Vegano'), ('vegetariano', 'Vegetariano'), ('celiaco', 'Celíaco')], max_length=11),
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('invitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitaciones.invitado')),
            ],
        ),
    ]
