# Generated by Django 4.1.7 on 2023-08-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0002_remove_invitado_apellido_remove_invitado_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitado',
            name='Dni',
        ),
        migrations.AlterField(
            model_name='invitado',
            name='email',
            field=models.EmailField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
