# Generated by Django 4.1.7 on 2023-09-09 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitaciones', '0003_remove_invitado_dni_alter_invitado_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tema',
            name='invitado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invitaciones.invitado'),
        ),
    ]
